### ISSUE TITLE
My Portfolio

### ISSUE THREAD

**Issue by Ankush-dev30** [ankushzaskar777/Home_Design_Frame#1]
<!DOCTYPE html>

<head>
    <title>Personal Portfolio website</title>
    <link rel="stylesheet" href="Style.css">
</head>
<nav>

    <body>
        <div class="data">
            <nav>
                <img src="/img/portfolio-png-png-image-186415.jpg" class="logo">
                <ul>
                    <li><a href="#">HOME</a></li>
                    <li><a href="#">ABOUT</a></li>
                    <li><a href="#">PORTFOLIO</a></li>
                    <li><a href="#">SERVICE</a></li>
                    <li><a href="#">HIRE ME</a></li>
                </ul>
            </nav>
            <div class="detail">
                <h1>I,m <br>Ankush<span>Zaskar</span></h1>
                <p>This Is My official portfolio website to show all
                    <br> Details and work experienceweb debvelopment
                </p>
                <a href="#">DOWNLOAD CV</a>
            </div>
            <div class="images">
                <img src="img/Shape.png.png" class="shape">
                <img src="img/anks.png.png" class="anks">
            </div>

    </body>

     </html>

**Comment by Ankush-dev30** [comment]
* {
    margin: 0;
    padding: 0;
    font-family: sans-serif;
    /* background: #eff4fd; */
}

.data {
    position: relative;
    width: 1000%;
    height: 100vh;
    background-color: #eff4fd;
}

.logo {
    height: 65px;
    width: 130px;
}

nav {
    display: flex;
    width: 84%;
    margin: auto;
    padding: 20px 0;
    align-items: center;
    justify-content: space-between;

}

nav ul li {
    display: inline-block;
    list-style: none;
    margin: 10px 20px;

}

nav ul li a {
    text-decoration: none;
    color: black;
    font-weight: bold;
}

nav ul li a:hover {
    color: rgb(255, 155, 4);

}

.detail {
    margin-left: 8%;
    margin-top: 13%;

}

.detail h1 {
    font-size: 50px;
    color: black;
    margin-bottom: 20px;
}

span {
    color: orange;
}

.detail p {
    color: #555;
    line-height: 22px;
}

.detail a {

    background: #212121;
    padding: 10px 18px;
    text-decoration: none;
    font-weight: bold;
    color: #fff;
    display: inline-block;
    margin: 30PX 0;
    border-radius: 5px;
}

.images {
    width: 45%;
    height: 80%;
    position: absolute;
    bottom: 0;
    right: 100px;
}

.images img {
    height: 100%;
    position: absolute;
    left: 50%;
    bottom: 0;
    transform: translateX(-50%);
    transition: bottom 1s, left 1s;
}

.images:hover .shape {
    bottom: 40px;
}

.images:hover .anks {
    left: 45%;
}

**Comment by ankushzaskar777** [comment]
* {
    margin: 0;
    padding: 0;
    font-family: sans-serif;
    /* background: #eff4fd; */
}

.data {
    position: relative;
    width: 1000%;
    height: 100vh;
    background-color: #eff4fd;
}

.logo {
    height: 65px;
    width: 130px;
}

nav {
    display: flex;
    width: 84%;
    margin: auto;
    padding: 20px 0;
    align-items: center;
    justify-content: space-between;

}

nav ul li {
    display: inline-block;
    list-style: none;
    margin: 10px 20px;

}

nav ul li a {
    text-decoration: none;
    color: black;
    font-weight: bold;
}

nav ul li a:hover {
    color: rgb(255, 155, 4);

}

.detail {
    margin-left: 8%;
    margin-top: 13%;

}

.detail h1 {
    font-size: 50px;
    color: black;
    margin-bottom: 20px;
}

span {
    color: orange;
}

.detail p {
    color: #555;
    line-height: 22px;
}

.detail a {

    background: #212121;
    padding: 10px 18px;
    text-decoration: none;
    font-weight: bold;
    color: #fff;
    display: inline-block;
    margin: 30PX 0;
    border-radius: 5px;
}

.images {
    width: 45%;
    height: 80%;
    position: absolute;
    bottom: 0;
    right: 100px;
}

.images img {
    height: 100%;
    position: absolute;
    left: 50%;
    bottom: 0;
    transform: translateX(-50%);
    transition: bottom 1s, left 1s;
}

.images:hover .shape {
    bottom: 40px;
}

.images:hover .anks {
    left: 45%;
}
